[package]
name = "puffin"
version = "0.1.0"
edition = "2021"

[features]
default = ["sancov_libafl", "introspection"]

# Logs each execution of __sanitizer_cov_trace_pc_guard*
sancov_pcguard_log = []
# Uses libafl for the instrumentation. sancov_pcguard_log and sancov_libafl are mutally exclusive
sancov_libafl = ["libafl_targets/sancov_pcguard_hitcounts"]

introspection = ["libafl/introspection"]

claims = []

[dependencies]

# LibAFL
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "2e746bf439629e4fe8fa47cf9f39acd1395c828f" }
# libafl_derive = "0.7.1"
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "2e746bf439629e4fe8fa47cf9f39acd1395c828f" }

# Logging
log = "0.4.17"
log4rs = "1.1.1"

# Other Dependencies
libc = { version = "0.2.126" }
clap = { version = "3.1.18", features = ["cargo"] }
rand = "0.8.5"
itertools = "0.10.3"
smallvec = "1.8.1"
serde = { version = "1.0.137", features = ["derive"] }
postcard = { version = "1.0.1", features = ["alloc"] }
once_cell = "1.12.0"
chrono = "0.4.19"
cfg-if = "1.0.0"
serde_json = "1.0.81" # Used for StatsMonitor TOOD: Hide behind feature flag


[dev-dependencies]
test-log = "0.2.10"
env_logger = "0.9.0"

